bindKey A {addWireMode}
bindKey B {createRoutingBlockage}
bindKey D {windowDeselect}
bindKey F {quickfit}
bindKey G {hierDown}
bindKey H {highlightInternalNets}
bindKey I {shiftInstance}
bindKey K {cleanRuler}
bindKey L {changeWireLayer}
bindKey M {mergeWire}
bindKey N {nextVia}
bindKey P {previousVia}
bindKey Q {summaryReport}
bindKey R {moveWireMode}
bindKey S {getWireInfo}
bindKey T {trimWire}
bindKey U {redo}
bindKey V {clearDrc}
bindKey W {changeWireWidth}
bindKey X {cutWireMode}
bindKey Y {createPlacementBlockage}
bindKey Z {zoomOut}
bindKey b {bindKeyForm}
bindKey c {copyMode}
bindKey d {popUpDelete}
bindKey e {popUpEdit}
bindKey f {fit}
bindKey g {hierUp}
bindKey h {highlightExternalNets}
bindKey i {spaceInstance}
bindKey k {createRuler}
bindKey m {resizeMode}
bindKey n {queryNext}
bindKey o {addViaMode}
bindKey p {queryPrevious}
bindKey q {attributeEditor}
bindKey r {rotateInstance}
bindKey s {stretchWireMode}
bindKey t {highlightTextTimingPath}
bindKey u {undo}
bindKey v {dbBrowser}
bindKey w {previousView}
bindKey x {zoomNextDrc}
bindKey y {nextView}
bindKey x {zoomNextDrc}
bindKey y {nextView}
bindKey z {zoomIn}
bindKey F2 {saveDesign}
bindKey F3 {displayForm}
bindKey F4 {popUpViaReplace}
bindKey F8 {printQuery}
bindKey F9 {metalBrightness}
bindKey Up {panUp}
bindKey F11 {metalLighter}
bindKey F12 {dimSelectionBg}
bindKey Down {panDown}
bindKey Left {panLeft}
bindKey Alt-0 {toggleM10Visibility}
bindKey Alt-1 {toggleM11Visibility}
bindKey Alt-2 {toggleM12Visibility}
bindKey Alt-3 {toggleM13Visibility}
bindKey Alt-4 {toggleM14Visibility}
bindKey Alt-5 {toggleM15Visibility}
bindKey Alt-6 {toggleM16Visibility}
bindKey Alt-7 {toggleM17Visibility}
bindKey Alt-8 {toggleM18Visibility}
bindKey Alt-9 {toggleM19Visibility}
bindKey Key-0 {toggleM0Visibility}
bindKey Key-1 {toggleM1Visibility}
bindKey Key-2 {toggleM2Visibility}
bindKey Key-3 {toggleM3Visibility}
bindKey Key-4 {toggleM4Visibility}
bindKey Key-5 {toggleM5Visibility}
bindKey Key-6 {toggleM6Visibility}
bindKey Key-7 {toggleM7Visibility}
bindKey Key-8 {toggleM8Visibility}
bindKey Key-9 {toggleM9Visibility}
bindKey Right {panRight}
bindKey space {selectNext}
bindKey Delete {deleteSelected}
bindKey Escape {selectMode}
bindKey Shift-Up {sprMoveWire n}
bindKey Backspace {deleteSelected}
bindKey Control-1 {goToSavedArea1}
bindKey Control-2 {goToSavedArea2}
bindKey Control-3 {goToSavedArea3}
bindKey Control-4 {goToSavedArea4}
bindKey Control-5 {goToSavedArea5}
bindKey Control-6 {goToSavedArea6}
bindKey Control-7 {goToSavedArea7}
bindKey Control-8 {goToSavedArea8}
bindKey Control-9 {goToSavedArea9}
bindKey Control-8 {goToSavedArea8}
bindKey Control-9 {goToSavedArea9}
bindKey Control-a {instAlignment}
bindKey Control-c {interrupt}
bindKey Control-d {deselectAll}
bindKey Control-f {findSelect}
bindKey Control-h {clearModuleNets}
bindKey Control-l {legalizeFloorplan}
bindKey Control-m {select_mode}
bindKey Control-n {snapFloorplan}
bindKey Control-p {ui::previous:save_zoomBox previousTool zoomBox}
bindKey Control-q {queryCongest}
bindKey Control-r {redraw}
bindKey Control-s {splitWire}
bindKey Control-w {deleteQueryObj}
bindKey Control-z {zoomSelected}
bindKey Control-Up {toPrevDrc}
bindKey Shift-Down {sprMoveWire s}
bindKey Shift-Left {sprMoveWire w}
bindKey Shift-Right {sprMoveWire e}
bindKey Shift-space {popupSelectionCandidatesMenu}
bindKey Control-Down {toNextDrc}
bindKey Control-Left {toPrevFolder}
bindKey Shift-Escape {cancel}
bindKey Control-Right {toNextFolder}
